plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'com.hypherionmc.modutils.modpublisher' version '2.2.1'
}

apply from: 'gradletools.gradle'

group = "com.github.mcjty"
version = project.version

base {
    archivesName = "${mod_id}-fabric-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(java_version))

tasks.named('updateDaemonJvm') {
    languageVersion = JavaLanguageVersion.of(Integer.parseInt(java_version))
}

if (System.getenv('BUILD_NUMBER') != null) {
    version += "-${System.getenv('BUILD_NUMBER')}"
}

repositories {
    mavenCentral()
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

tasks.withType(Jar).configureEach {
    includeEmptyDirs = false
}

loom {
    def aw = file("src/main/resources/META-INF/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
        datagen {
            server()
            name 'Fabric Data Generation'
            vmArg '-Dfabric-api.datagen'
            vmArg '-Dfabric-api.datagen.output-dir=' + file('src/generated/resources').absolutePath
            vmArg '-Dfabric-api.datagen.modid=' + mod_id
            runDir 'build/datagen'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api_port_version}"
}

modpublisher([], ['fabric-api', 'forge-config-api-port'], [], ['fabric-api', 'forge-config-api-port'], [])

processResources {
    def expandProps = [
            'version'              : version,
            'mod_id'               : mod_id,
            'mod_name'             : mod_name,
            'minecraft_version'    : minecraft_version,
            'fabric_loader_version': fabric_loader_version,
            'java_version'         : java_version
    ]
    filesMatching('fabric.mod.json') {
        expand expandProps
    }
    inputs.properties(expandProps)
}

tasks.register('apiJar', Jar) {
    archiveClassifier = "api"
    from(sourceSets.main.output) {
        include "mcjty/lostcities/api/**"
    }
}

artifacts {
    archives apiJar
}

publishing {
    publications.create('mavenJava', MavenPublication) {
        from components.java
        artifact apiJar

        artifactId = "lostcities"
        pom {
            name = 'LostCities'
            description = 'Lost Cities'
            scm {
                url = 'https://github.com/McJtyMods/LostCities'
                connection = 'scm:git:git@github.com:McJtyMods/LostCities.git'
                developerConnection = 'scm:git:git@github.com:McJtyMods/LostCities.git'
            }
            issueManagement {
                system = 'github'
                url = 'https://github.com/McJtyMods/LostCities/issues'
            }
            licenses {
                license {
                    name = 'MIT'
                    distribution = 'repo'
                }
            }
            developers {
                developer {
                    id = 'McJty'
                    name = 'McJty'
                    roles = ['developer']
                }
            }
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                name = 'local'
                url = 'file://' + System.getenv('local_maven')
            }
        }
    }
}
