mod_id=lostcities
mod_name=LostCities
version=26.2-11.0.0-fabric
curse_type=beta
projectId=269024
projectSlug=the-lost-cities
modrinthId=8VDCUS3b
github_project=McJtyMods/LostCities

org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

# Minecraft / Fabric
minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_version=0.155.2+26.2
loom_version=1.17.17
forge_config_api_port_version=26.2.1
java_version=25
